#!/bin/bash
Logdir=/home/centos/app_logs
Date=$(date +%F:%H:%M:%S)
Logfile=Logdir/$0-$Date.log
USERID=$(id -u)
if [ $USERID -ne 0 ]
then
 echo "please run the script with root user"
 exit 1
fi
validate() {
  if [ $1 -ne 0 ]
  then
   echo "$2.. failed"
  else
   echo "$2.. Success"
  fi
}

for i in $@
do
 yum list installed $i
 if [$? -ne 0 ]
 then
  echo "$i is not installed ,let install $i"
  yum install $i -y &>>Logfile
  validate()$? "$i installation"
  fi
done

